"""Editorial hierarchy for the 500-cluster BERTopic run.

This is intentionally a human-authored configuration.  The raw BERTopic
clusters remain the source of episode membership; this module only defines
which clusters can safely be merged into user-facing topics and which should
be withheld because they are generic, mixed, or artefactual.

The proposal was reviewed using the cluster labels, c-TF-IDF keywords,
representative passages, source episodes, and cluster/episode counts.  Labels
generated by the LLM were treated as reading aids rather than ground truth.
"""

from __future__ import annotations


# A specific topic may contain several raw clusters only when they make the
# same useful promise to a visitor.  IDs are from data/nlp/k500.
SPECIFIC_TOPICS: dict[str, dict[str, object]] = {
    "forfattarskap": {"label": "Författarskap och skrivande", "broad": "Kultur och medier", "raw": [0, 58]},
    "litteratur": {"label": "Litteratur och läsande", "broad": "Kultur och medier", "raw": [88, 490]},
    "deckare": {"label": "Deckare och kriminalromaner", "broad": "Kultur och medier", "raw": [165, 469]},
    "poesi": {"label": "Poesi och dikt", "broad": "Kultur och medier", "raw": [10]},
    "skola": {"label": "Skola, lärare och elever", "broad": "Utbildning och arbetsliv", "raw": [6, 161, 275]},
    "skoltid_utanforskap": {"label": "Utanförskap under skoltiden", "broad": "Utbildning och arbetsliv", "raw": [38]},
    "skolsegregation": {"label": "Skolsegregation och friskolor", "broad": "Utbildning och arbetsliv", "raw": [214, 453]},
    "dyslexi_autism": {"label": "Dyslexi, autism och lärande", "broad": "Hälsa och liv", "raw": [427]},
    "universitet": {"label": "Universitet och studier", "broad": "Utbildning och arbetsliv", "raw": [137]},
    "psykisk_ohalsa": {"label": "Psykisk ohälsa och psykiatri", "broad": "Hälsa och liv", "raw": [8, 151, 300]},
    "aterhamtning": {"label": "Stress, utmattning och återhämtning", "broad": "Hälsa och liv", "raw": [19, 75]},
    "sorg": {"label": "Sorg och förlust", "broad": "Relationer och familj", "raw": [25, 40, 46, 77, 152, 319]},
    "cancer": {"label": "Cancer och allvarlig sjukdom", "broad": "Hälsa och liv", "raw": [26]},
    "skador_operationer": {"label": "Skador, smärta och operationer", "broad": "Hälsa och liv", "raw": [273]},
    "aldrande": {"label": "Åldrande och äldreomsorg", "broad": "Hälsa och liv", "raw": [102, 321]},
    "hjarnan": {"label": "Hjärnan och neurovetenskap", "broad": "Vetenskap och teknik", "raw": [277, 369]},
    "somn": {"label": "Sömn och dygnsrytm", "broad": "Hälsa och liv", "raw": [415]},
    "infektioner": {"label": "Infektioner och immunförsvar", "broad": "Hälsa och liv", "raw": [408]},
    "halsa_livsstil": {"label": "Hälsa och livsstil", "broad": "Hälsa och liv", "raw": [410]},
    "fertilitet": {"label": "Fertilitet, graviditet och förlossning", "broad": "Hälsa och liv", "raw": [128, 402]},
    "mens_hormoner": {"label": "Mens, hormoner och klimakteriet", "broad": "Hälsa och liv", "raw": [315, 437]},
    "organdonation": {"label": "Organdonation och transplantation", "broad": "Hälsa och liv", "raw": [449]},
    "medicinsk_teknik": {"label": "Medicinsk teknik och vävnadsreparation", "broad": "Vetenskap och teknik", "raw": [466]},
    "mammor": {"label": "Mödrar och moderskap", "broad": "Relationer och familj", "raw": [14, 15, 94, 112]},
    "pappor": {"label": "Fäder och faderskap", "broad": "Relationer och familj", "raw": [60, 62]},
    "slaktrotter": {"label": "Släktrötter och familjehistoria", "broad": "Relationer och familj", "raw": [22, 64, 202, 459]},
    "foraldraskap": {"label": "Föräldraskap och barns uppväxt", "broad": "Relationer och familj", "raw": [122, 236, 250]},
    "foraldraledighet": {"label": "Föräldraledighet och jämställt föräldraskap", "broad": "Relationer och familj", "raw": [208]},
    "adoption": {"label": "Adoption och internationella adoptioner", "broad": "Relationer och familj", "raw": [113, 168, 375]},
    "karlek": {"label": "Kärlek och förälskelse", "broad": "Relationer och familj", "raw": [116, 184]},
    "separation": {"label": "Parrelationer och separationer", "broad": "Relationer och familj", "raw": [147, 205]},
    "sexuellt_vald": {"label": "Sexuella övergrepp och metoo", "broad": "Samhälle och identitet", "raw": [67, 254]},
    "konsroller": {"label": "Könsroller och kvinnors frihet", "broad": "Samhälle och identitet", "raw": [84]},
    "feminism": {"label": "Feminism och jämställdhet", "broad": "Samhälle och identitet", "raw": [148, 219, 354, 364]},
    "kvinnor_ledarskap": {"label": "Kön och ledarskap i näringslivet", "broad": "Utbildning och arbetsliv", "raw": [238]},
    "hbtq": {"label": "HBTQ-identitet och sexualitet", "broad": "Samhälle och identitet", "raw": [284]},
    "rasism": {"label": "Rasism och diskriminering", "broad": "Samhälle och identitet", "raw": [106, 405]},
    "svenskhet": {"label": "Svenskhet och tillhörighet", "broad": "Samhälle och identitet", "raw": [81, 115, 210]},
    "migration": {"label": "Migration, flykt och exil", "broad": "Samhälle och identitet", "raw": [30, 107, 132]},
    "integration": {"label": "Integration och samhällsgemenskap", "broad": "Samhälle och identitet", "raw": [281]},
    "sprak_identitet": {"label": "Språk, dialekter och identitet", "broad": "Samhälle och identitet", "raw": [127, 322, 399, 481]},
    "finlandssvenskt": {"label": "Finlandssvensk och finsk identitet", "broad": "Samhälle och identitet", "raw": [283]},
    "kurdiskt": {"label": "Kurdisk historia och identitet", "broad": "Internationellt och historia", "raw": [329]},
    "iransk_flykt": {"label": "Iran, flykt och identitet", "broad": "Internationellt och historia", "raw": [279]},
    "teater": {"label": "Teater och skådespeleri", "broad": "Kultur och medier", "raw": [31, 43, 80, 290, 320]},
    "revy": {"label": "Revy och scenföreställningar", "broad": "Kultur och medier", "raw": [49, 175]},
    "film": {"label": "Film och filmskapande", "broad": "Kultur och medier", "raw": [78, 212, 251, 259, 263, 386]},
    "bildkonst": {"label": "Bildkonst och konstnärskap", "broad": "Kultur och medier", "raw": [129, 255, 316, 353, 365]},
    "arkitektur": {"label": "Arkitektur och stadsbyggnad", "broad": "Kultur och medier", "raw": [308, 325]},
    "mode": {"label": "Mode, kläder och design", "broad": "Kultur och medier", "raw": [171, 278, 326, 388, 400]},
    "dans": {"label": "Dans och koreografi", "broad": "Kultur och medier", "raw": [146]},
    "humor": {"label": "Humor, standup och satir", "broad": "Kultur och medier", "raw": [23, 231]},
    "journalistik": {"label": "Journalistik och redaktionsarbete", "broad": "Kultur och medier", "raw": [95, 288, 493]},
    "radio": {"label": "Svensk radiohistoria", "broad": "Kultur och medier", "raw": [125]},
    "television": {"label": "Television och programledarskap", "broad": "Kultur och medier", "raw": [89, 276]},
    "klassisk_musik": {"label": "Klassisk musik och orkestrar", "broad": "Musik", "raw": [85, 99, 135, 144, 286, 358]},
    "opera": {"label": "Opera och operaliv", "broad": "Musik", "raw": [121, 265]},
    "jazz": {"label": "Jazz och improviserad musik", "broad": "Musik", "raw": [16, 241]},
    "rock_pop": {"label": "Rock- och pophistoria", "broad": "Musik", "raw": [69, 104, 119, 123, 282, 392]},
    "artistliv": {"label": "Artistliv, band och turnéer", "broad": "Musik", "raw": [37, 52, 72, 143, 149, 183, 187]},
    "har": {"label": "Hår, frisyrer och håravfall", "broad": "Hälsa och liv", "raw": [337]},
    "latskrivande": {"label": "Låtskrivande och musikskapande", "broad": "Musik", "raw": [45, 79, 105, 110, 483]},
    "musikbransch": {"label": "Musikbranschen och skivkontrakt", "broad": "Musik", "raw": [32, 166, 201]},
    "melodifestivalen": {"label": "Melodifestivalen och Eurovision", "broad": "Musik", "raw": [170]},
    "folkmusik": {"label": "Folkmusik och världsmusik", "broad": "Musik", "raw": [409]},
    "taube_visor": {"label": "Visor och Evert Taube", "broad": "Musik", "raw": [486]},
    "politik": {"label": "Svensk politik och riksdagen", "broad": "Politik och ekonomi", "raw": [57, 138, 226, 256]},
    "demokrati": {"label": "Demokrati, rättsstat och yttrandefrihet", "broad": "Politik och ekonomi", "raw": [142]},
    "eu": {"label": "EU och europeiskt samarbete", "broad": "Internationellt och historia", "raw": [233, 355]},
    "trump": {"label": "Donald Trump och amerikansk politik", "broad": "Internationellt och historia", "raw": [229]},
    "nato": {"label": "Nato och säkerhetspolitik", "broad": "Internationellt och historia", "raw": [341, 411]},
    "karnvapen": {"label": "Kärnvapen och nedrustning", "broad": "Internationellt och historia", "raw": [114, 324]},
    "diplomati": {"label": "Diplomati och fredsarbete", "broad": "Internationellt och historia", "raw": [182]},
    "krig_flykt": {"label": "Krig, flykt och civila", "broad": "Internationellt och historia", "raw": [24, 303]},
    "ukraina": {"label": "Rysslands krig mot Ukraina", "broad": "Internationellt och historia", "raw": [178, 343]},
    "ryssland_sovjet": {"label": "Ryssland och Sovjetunionen", "broad": "Internationellt och historia", "raw": [153, 347]},
    "forintelsen": {"label": "Förintelsen och andra världskriget", "broad": "Internationellt och historia", "raw": [101, 390, 396, 447]},
    "wallenberg": {"label": "Raoul Wallenberg och räddningsinsatser", "broad": "Internationellt och historia", "raw": [361]},
    "bosnien": {"label": "Bosnienkriget och Jugoslaviens upplösning", "broad": "Internationellt och historia", "raw": [268]},
    "afghanistan": {"label": "Afghanistan och talibanerna", "broad": "Internationellt och historia", "raw": [356, 487]},
    "irak": {"label": "Irakkriget och Saddam Hussein", "broad": "Internationellt och historia", "raw": [287]},
    "israel_palestina": {"label": "Israel och Palestina", "broad": "Internationellt och historia", "raw": [266, 467]},
    "egypten": {"label": "Egypten och den arabiska våren", "broad": "Internationellt och historia", "raw": [366]},
    "latinamerika": {"label": "Latinamerika, diktaturer och exil", "broad": "Internationellt och historia", "raw": [224, 370, 472]},
    "afrika_politik": {"label": "Afrikansk politik efter kolonialismen", "broad": "Internationellt och historia", "raw": [334]},
    "apartheid": {"label": "Apartheid och Nelson Mandela", "broad": "Internationellt och historia", "raw": [416]},
    "slaveri_kolonialism": {"label": "Slaveri och kolonialism i Afrika", "broad": "Internationellt och historia", "raw": [438]},
    "kongo": {"label": "Kongo och humanitära kriser", "broad": "Internationellt och historia", "raw": [318]},
    "utoya": {"label": "Utøya och 22 juli-attentatet", "broad": "Internationellt och historia", "raw": [380]},
    "sextioatt_rorelsen": {"label": "1968-rörelsen och Vietnamkriget", "broad": "Internationellt och historia", "raw": [285]},
    "norge_1905": {"label": "Norge och unionsupplösningen 1905", "broad": "Internationellt och historia", "raw": [439]},
    "ungern_1956": {"label": "Ungernrevolten 1956", "broad": "Internationellt och historia", "raw": [470]},
    "varnplikt": {"label": "Värnplikt och militärtjänst", "broad": "Internationellt och historia", "raw": [304]},
    "brott": {"label": "Brottslighet och kriminella nätverk", "broad": "Samhälle och identitet", "raw": [100, 336]},
    "polis": {"label": "Polisarbete och kriminalutredningar", "broad": "Samhälle och identitet", "raw": [367, 379]},
    "rattsvasende": {"label": "Domstolar och försvarsadvokater", "broad": "Samhälle och identitet", "raw": [247]},
    "fangelse": {"label": "Fängelse och kriminalvård", "broad": "Samhälle och identitet", "raw": [323, 435]},
    "drogpolitik": {"label": "Narkotika och drogpolitik", "broad": "Samhälle och identitet", "raw": [431]},
    "ekonomi": {"label": "Banker, räntor och finanskriser", "broad": "Politik och ekonomi", "raw": [93, 130, 159]},
    "kapitalism": {"label": "Kapitalism och globalisering", "broad": "Politik och ekonomi", "raw": [220, 314]},
    "foretagande": {"label": "Entreprenörskap och företagsbyggande", "broad": "Utbildning och arbetsliv", "raw": [186, 194, 228, 252, 310, 350, 359, 394, 471, 488]},
    "ledarskap": {"label": "Ledarskap och arbetsliv", "broad": "Utbildning och arbetsliv", "raw": [211, 299]},
    "valgorenhet": {"label": "Välgörenhet och filantropi", "broad": "Politik och ekonomi", "raw": [298]},
    "fattigdom": {"label": "Fattigdom och global utveckling", "broad": "Politik och ekonomi", "raw": [271, 421]},
    "internet": {"label": "Internet och digitalisering", "broad": "Vetenskap och teknik", "raw": [332, 468, 480]},
    "ai": {"label": "Artificiell intelligens och robotik", "broad": "Vetenskap och teknik", "raw": [351, 372]},
    "spel": {"label": "Datorspel och spelutveckling", "broad": "Vetenskap och teknik", "raw": [393, 398, 444]},
    "rymden": {"label": "Rymden och astronomi", "broad": "Vetenskap och teknik", "raw": [306, 338, 360, 371, 403]},
    "forskning": {"label": "Forskning och naturvetenskap", "broad": "Vetenskap och teknik", "raw": [237, 340]},
    "evolution": {"label": "Evolution, dna och människans historia", "broad": "Vetenskap och teknik", "raw": [342]},
    "svampar": {"label": "Svampar och ekologi", "broad": "Natur och klimat", "raw": [401]},
    "filosofi": {"label": "Filosofi, medvetande och moral", "broad": "Tro och livsåskådning", "raw": [48, 134, 180, 294]},
    "kristendom": {"label": "Kristendom, kyrka och prästerskap", "broad": "Tro och livsåskådning", "raw": [173, 190, 198, 253, 270, 312, 376, 422, 460, 498]},
    "islam": {"label": "Islam och muslimsk identitet", "broad": "Tro och livsåskådning", "raw": [333, 497]},
    "judisk_identitet": {"label": "Judisk identitet och antisemitism", "broad": "Tro och livsåskådning", "raw": [397]},
    "jul": {"label": "Jul och svenska jultraditioner", "broad": "Tro och livsåskådning", "raw": [257, 335]},
    "ensamhet": {"label": "Ensamhet och social tillhörighet", "broad": "Relationer och familj", "raw": [313]},
    "covid": {"label": "Covid-19 och pandemin", "broad": "Hälsa och liv", "raw": [240, 258]},
    "ebola": {"label": "Ebola och epidemibekämpning", "broad": "Hälsa och liv", "raw": [352]},
    "svenska_akademien": {"label": "Svenska Akademien", "broad": "Kultur och medier", "raw": [307]},
    "antikviteter": {"label": "Antikviteter och kulturföremål", "broad": "Kultur och medier", "raw": [395]},
    "ester_blenda": {"label": "Ester Blenda Nordström och pionjärjournalistik", "broad": "Kultur och medier", "raw": [424]},
    "monarki": {"label": "Kungahuset och monarkin", "broad": "Politik och ekonomi", "raw": [429]},
    "politisk_teater": {"label": "Politisk teater", "broad": "Kultur och medier", "raw": [448]},
    "tatuering": {"label": "Tatuering och tatueringskonst", "broad": "Kultur och medier", "raw": [451]},
    "lek": {"label": "Lekens betydelse", "broad": "Relationer och familj", "raw": [457]},
    "matlagning": {"label": "Matlagning, bakning och smaker", "broad": "Mat och livsstil", "raw": [98, 158, 245, 391, 478]},
    "restaurang": {"label": "Kockar och restaurangliv", "broad": "Mat och livsstil", "raw": [222, 482]},
    "vin_alkohol": {"label": "Vin, alkohol och dryckeskultur", "broad": "Mat och livsstil", "raw": [348, 383]},
    "klimat": {"label": "Klimatkrisen och utsläppen", "broad": "Natur och klimat", "raw": [296, 297, 417, 425]},
    "hallbarhet": {"label": "Hållbar utveckling och resiliens", "broad": "Natur och klimat", "raw": [196, 242, 413]},
    "gron_industri": {"label": "Grön industriomställning", "broad": "Natur och klimat", "raw": [378]},
    "mat_klimat": {"label": "Matens klimatpåverkan", "broad": "Natur och klimat", "raw": [430]},
    "glaciarer": {"label": "Glaciärer och ett varmare klimat", "broad": "Natur och klimat", "raw": [433]},
    "biologisk_mangfald": {"label": "Biologisk mångfald och arter", "broad": "Natur och klimat", "raw": [181, 293, 419]},
    "skog": {"label": "Skog och naturvård", "broad": "Natur och klimat", "raw": [108, 434]},
    "djur": {"label": "Djur, djurparker och djurskydd", "broad": "Natur och klimat", "raw": [169, 389, 458]},
    "hundar": {"label": "Hundar och hundägande", "broad": "Natur och klimat", "raw": [221]},
    "hav_fiske": {"label": "Havsmiljö och fiske", "broad": "Natur och klimat", "raw": [373, 412]},
    "tradgard": {"label": "Trädgård och odling", "broad": "Natur och klimat", "raw": [230]},
    "vader": {"label": "Väder och meteorologi", "broad": "Natur och klimat", "raw": [267, 387, 455]},
    "norrland": {"label": "Norrland, älvar och glesbygd", "broad": "Platser och resor", "raw": [76, 86, 295]},
    "skargard": {"label": "Öar, skärgård och kustliv", "broad": "Platser och resor", "raw": [189, 246, 418]},
    "new_york": {"label": "New York och storstadsliv", "broad": "Platser och resor", "raw": [83, 232, 317]},
    "frankrike": {"label": "Frankrike och fransk kultur", "broad": "Platser och resor", "raw": [260, 382, 446]},
    "italien": {"label": "Italien och italiensk kultur", "broad": "Platser och resor", "raw": [305]},
    "afrika_resor": {"label": "Resor och erfarenheter i Afrika", "broad": "Platser och resor", "raw": [118]},
    "kina": {"label": "Kina och kinesisk kultur", "broad": "Platser och resor", "raw": [331, 443]},
    "kanada": {"label": "Kanada och kanadensisk kultur", "broad": "Platser och resor", "raw": [463]},
    "resor_transport": {"label": "Resor och transportmissöden", "broad": "Platser och resor", "raw": [59]},
    "bilar": {"label": "Bilar och bilkörning", "broad": "Platser och resor", "raw": [103]},
    "usa_resor": {"label": "Resor och möten med USA", "broad": "Platser och resor", "raw": [197]},
    "flyg": {"label": "Flygning och flygare", "broad": "Platser och resor", "raw": [309]},
    "segling": {"label": "Segling och livet till havs", "broad": "Äventyr och sport", "raw": [225, 274, 339]},
    "aventyr": {"label": "Expeditioner och vildmarksäventyr", "broad": "Äventyr och sport", "raw": [136, 311]},
    "elitidrott": {"label": "Elitidrott och mästerskap", "broad": "Äventyr och sport", "raw": [156, 167, 185, 213, 261, 462]},
    "parasport": {"label": "Parasport och Paralympics", "broad": "Äventyr och sport", "raw": [97]},
    "sportjournalistik": {"label": "Sportjournalistik och idrottsreferat", "broad": "Kultur och medier", "raw": [346]},
    "fotboll": {"label": "Idrottskarriärer och tränarskap", "broad": "Äventyr och sport", "raw": [172, 227, 327, 330, 345, 363]},
    "hockey": {"label": "Ishockey och NHL", "broad": "Äventyr och sport", "raw": [235, 494]},
    "basket": {"label": "Basket, volleyboll och handboll", "broad": "Äventyr och sport", "raw": [216, 349]},
    "tennis": {"label": "Tennis", "broad": "Äventyr och sport", "raw": [344]},
    "golf": {"label": "Golf", "broad": "Äventyr och sport", "raw": [377]},
    "ridsport": {"label": "Ridsport och hästar", "broad": "Äventyr och sport", "raw": [157, 414]},
    "skidor": {"label": "Skidåkning och alpint", "broad": "Äventyr och sport", "raw": [204, 456]},
    "boxning": {"label": "Boxning och kampsport", "broad": "Äventyr och sport", "raw": [262]},
    "motorsport": {"label": "Bilar och motorsport", "broad": "Äventyr och sport", "raw": [292, 385]},
    "doping": {"label": "Dopning inom idrotten", "broad": "Äventyr och sport", "raw": [426, 461]},
    "schack": {"label": "Schack", "broad": "Äventyr och sport", "raw": [440]},
    "simning": {"label": "Simning och att lära sig simma", "broad": "Äventyr och sport", "raw": [406]},
    "traning": {"label": "Träning och motion", "broad": "Äventyr och sport", "raw": [407]},
    "hojdhopp": {"label": "Höjdhopp", "broad": "Äventyr och sport", "raw": [464]},
    "langlopp_cykling": {"label": "Långlopp och cykling", "broad": "Äventyr och sport", "raw": [485]},
}


# These clusters are intentionally not exposed as topics.  The distinctions
# make later review possible without pretending that every K-means partition
# is semantically useful.
EXCLUDED: dict[str, list[int]] = {
    "generic_personal_narrative": [1, 2, 3, 5, 9, 11, 13, 17, 20, 21, 28, 29, 33, 34, 36, 39, 42, 44, 47, 51, 53, 54, 55, 61, 63, 68, 70, 71, 74, 82, 87, 91, 92, 96, 109, 111, 117, 120, 124, 133, 139, 140, 145, 150, 154, 155, 160, 163, 176, 177, 179, 188, 191, 203, 207, 217, 223, 234, 244, 249, 264, 289, 454, 474, 477, 479, 495],
    "mixed_or_name_driven": [18, 27, 56, 65, 66, 90, 126, 131, 141, 162, 192, 193, 199, 200, 215, 218, 239, 243, 248, 272, 301, 302, 328, 357, 362, 368, 374, 381, 384, 404, 420, 423, 428, 432, 436, 441, 442, 450, 452, 465, 473, 475, 476, 489, 496],
    "song_or_transcription_artifact": [4, 7, 12, 35, 41, 50, 73, 164, 174, 195, 206, 209, 269, 280, 291, 445, 484, 491],
    "too_narrow_or_not_reusable": [492, 499],
}


def validate() -> None:
    """Raise when an ID is missing, duplicated, or outside the K500 run."""

    assigned = [raw_id for topic in SPECIFIC_TOPICS.values() for raw_id in topic["raw"]]
    excluded = [raw_id for ids in EXCLUDED.values() for raw_id in ids]
    all_ids = assigned + excluded
    duplicates = sorted({raw_id for raw_id in all_ids if all_ids.count(raw_id) > 1})
    missing = sorted(set(range(500)) - set(all_ids))
    extra = sorted(set(all_ids) - set(range(500)))
    if duplicates or missing or extra:
        raise ValueError(f"Invalid hierarchy: duplicates={duplicates}, missing={missing}, extra={extra}")


validate()


# The K-means clusters for these historical programmes were too mixed to
# expose wholesale.  The complete transcripts nevertheless support these
# conservative, episode-level additions.  Shares are editorial weights used
# only for ranking/display; no raw chunk membership is changed.
MANUAL_EPISODE_TOPICS: dict[int, dict[str, float]] = {
    557543: {"poesi": 0.55, "karlek": 0.30},
    1569347: {"poesi": 0.55, "ensamhet": 0.30, "karlek": 0.15},
}


# Cluster-level topic names are not enough for sports: a single chunk can
# mention another sport in passing. These rules require concentrated,
# topic-specific evidence across an episode's chunks, without naming people.
TOPIC_EVIDENCE_RULES: dict[str, dict[str, object]] = {
    "boxning": {
        "min_chunks": 3,
        "terms": ["boxning", "boxare", "boxas", "proffsboxare", "mma", "sparring", "fighter", "gonggongen"],
        "min_distinct_terms": 2,
    },
    "fotboll": {
        "min_chunks": 2,
        "terms": ["fotboll", "fotbolls", "allsvenskan", "landslag", "premier league", "champions league", "zlatan", "målvakt", "forward", "degerfors", "manchester", "lazio", "benfica", "sampdoria", "juventus"],
        "min_distinct_terms": 2,
    },
}
